POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Choirul Anam",
    "username": "benihime",
    "email": "benihime@gmail.com",
    "password": "irul123",
    "gender": "M",
    "birth_place": "Pasuruan",
    "birth_date": "2003-11-15",
    "addres": "Gajahbendo, Kec. Beji, Kab. Pasuruan",
    "phone_num": "083111037617"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "benihime",
    "password": "irul123"
}

###
GET http://localhost:3000/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlbmloaW1lQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MzUwODE1NDUsImV4cCI6MTczNTA4Mjc0NX0.2DilVSqwM2ldaNFFUFKkBRDDRnuLD2ePlRyLn0frXOQ

###
GET http://localhost:3000/category/get













